#!/bin/sh -e

# debirf module: motd
# custom /etc/motd file
#
# The debirf scripts were written by
# Jameson Rollins <jrollins@fifthhorseman.net>
# and
# Daniel Kahn Gillmor <dkg@fifthhorseman.net>.
#
# They are Copyright 2007-2016, and are all released under the GPL,
# version 3 or later.

cat <<EOF > "${DEBIRF_ROOT}/etc/motd"
==================================================
Welcome to debirf: DEBian on InitRamFs
==================================================
EOF
